(cl:defpackage spot_control-srv
  (:use )
  (:export
   "JOINTCONTROL"
   "<JOINTCONTROL-REQUEST>"
   "JOINTCONTROL-REQUEST"
   "<JOINTCONTROL-RESPONSE>"
   "JOINTCONTROL-RESPONSE"
   "MULTIPLIER"
   "<MULTIPLIER-REQUEST>"
   "MULTIPLIER-REQUEST"
   "<MULTIPLIER-RESPONSE>"
   "MULTIPLIER-RESPONSE"
  ))

