// Generated by gencpp from file spot_control/jointControlResponse.msg
// DO NOT EDIT!


#ifndef SPOT_CONTROL_MESSAGE_JOINTCONTROLRESPONSE_H
#define SPOT_CONTROL_MESSAGE_JOINTCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_control
{
template <class ContainerAllocator>
struct jointControlResponse_
{
  typedef jointControlResponse_<ContainerAllocator> Type;

  jointControlResponse_()
    : success(false)
    , message()  {
    }
  jointControlResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::spot_control::jointControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_control::jointControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jointControlResponse_

typedef ::spot_control::jointControlResponse_<std::allocator<void> > jointControlResponse;

typedef boost::shared_ptr< ::spot_control::jointControlResponse > jointControlResponsePtr;
typedef boost::shared_ptr< ::spot_control::jointControlResponse const> jointControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_control::jointControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_control::jointControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_control::jointControlResponse_<ContainerAllocator1> & lhs, const ::spot_control::jointControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_control::jointControlResponse_<ContainerAllocator1> & lhs, const ::spot_control::jointControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_control::jointControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_control::jointControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::jointControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::jointControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::jointControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::jointControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_control::jointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::spot_control::jointControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_control::jointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_control/jointControlResponse";
  }

  static const char* value(const ::spot_control::jointControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_control::jointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success  # Whether the joint commands were successfully executed\n"
"string message\n"
;
  }

  static const char* value(const ::spot_control::jointControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_control::jointControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_control::jointControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_control::jointControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_CONTROL_MESSAGE_JOINTCONTROLRESPONSE_H
