// Generated by gencpp from file spot_control/jointControl.msg
// DO NOT EDIT!


#ifndef SPOT_CONTROL_MESSAGE_JOINTCONTROL_H
#define SPOT_CONTROL_MESSAGE_JOINTCONTROL_H

#include <ros/service_traits.h>


#include <spot_control/jointControlRequest.h>
#include <spot_control/jointControlResponse.h>


namespace spot_control
{

struct jointControl
{

typedef jointControlRequest Request;
typedef jointControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jointControl
} // namespace spot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_control::jointControl > {
  static const char* value()
  {
    return "ba9d5e6dc2edb0be1ff0f44aa41279a2";
  }

  static const char* value(const ::spot_control::jointControl&) { return value(); }
};

template<>
struct DataType< ::spot_control::jointControl > {
  static const char* value()
  {
    return "spot_control/jointControl";
  }

  static const char* value(const ::spot_control::jointControl&) { return value(); }
};


// service_traits::MD5Sum< ::spot_control::jointControlRequest> should match
// service_traits::MD5Sum< ::spot_control::jointControl >
template<>
struct MD5Sum< ::spot_control::jointControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_control::jointControl >::value();
  }
  static const char* value(const ::spot_control::jointControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_control::jointControlRequest> should match
// service_traits::DataType< ::spot_control::jointControl >
template<>
struct DataType< ::spot_control::jointControlRequest>
{
  static const char* value()
  {
    return DataType< ::spot_control::jointControl >::value();
  }
  static const char* value(const ::spot_control::jointControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_control::jointControlResponse> should match
// service_traits::MD5Sum< ::spot_control::jointControl >
template<>
struct MD5Sum< ::spot_control::jointControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_control::jointControl >::value();
  }
  static const char* value(const ::spot_control::jointControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_control::jointControlResponse> should match
// service_traits::DataType< ::spot_control::jointControl >
template<>
struct DataType< ::spot_control::jointControlResponse>
{
  static const char* value()
  {
    return DataType< ::spot_control::jointControl >::value();
  }
  static const char* value(const ::spot_control::jointControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_CONTROL_MESSAGE_JOINTCONTROL_H
