// Generated by gencpp from file spot_control/jointControlRequest.msg
// DO NOT EDIT!


#ifndef SPOT_CONTROL_MESSAGE_JOINTCONTROLREQUEST_H
#define SPOT_CONTROL_MESSAGE_JOINTCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_control
{
template <class ContainerAllocator>
struct jointControlRequest_
{
  typedef jointControlRequest_<ContainerAllocator> Type;

  jointControlRequest_()
    : joint_angles()  {
    }
  jointControlRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::spot_control::jointControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_control::jointControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct jointControlRequest_

typedef ::spot_control::jointControlRequest_<std::allocator<void> > jointControlRequest;

typedef boost::shared_ptr< ::spot_control::jointControlRequest > jointControlRequestPtr;
typedef boost::shared_ptr< ::spot_control::jointControlRequest const> jointControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_control::jointControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_control::jointControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_control::jointControlRequest_<ContainerAllocator1> & lhs, const ::spot_control::jointControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_control::jointControlRequest_<ContainerAllocator1> & lhs, const ::spot_control::jointControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_control::jointControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_control::jointControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::jointControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::jointControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::jointControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::jointControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_control::jointControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eebf9cc7d525d143ad033b65dacb648";
  }

  static const char* value(const ::spot_control::jointControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eebf9cc7d525d14ULL;
  static const uint64_t static_value2 = 0x3ad033b65dacb648ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_control::jointControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_control/jointControlRequest";
  }

  static const char* value(const ::spot_control::jointControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_control::jointControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float64[] joint_angles  # A list of target angles for the joints of all legs\n"
;
  }

  static const char* value(const ::spot_control::jointControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_control::jointControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_control::jointControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_control::jointControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_CONTROL_MESSAGE_JOINTCONTROLREQUEST_H
