// Generated by gencpp from file spot_control/multiplierResponse.msg
// DO NOT EDIT!


#ifndef SPOT_CONTROL_MESSAGE_MULTIPLIERRESPONSE_H
#define SPOT_CONTROL_MESSAGE_MULTIPLIERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_control
{
template <class ContainerAllocator>
struct multiplierResponse_
{
  typedef multiplierResponse_<ContainerAllocator> Type;

  multiplierResponse_()
    : result(0)  {
    }
  multiplierResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::spot_control::multiplierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_control::multiplierResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multiplierResponse_

typedef ::spot_control::multiplierResponse_<std::allocator<void> > multiplierResponse;

typedef boost::shared_ptr< ::spot_control::multiplierResponse > multiplierResponsePtr;
typedef boost::shared_ptr< ::spot_control::multiplierResponse const> multiplierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_control::multiplierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_control::multiplierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_control::multiplierResponse_<ContainerAllocator1> & lhs, const ::spot_control::multiplierResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_control::multiplierResponse_<ContainerAllocator1> & lhs, const ::spot_control::multiplierResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spot_control::multiplierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_control::multiplierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::multiplierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_control::multiplierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::multiplierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_control::multiplierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_control::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::spot_control::multiplierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_control::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_control/multiplierResponse";
  }

  static const char* value(const ::spot_control::multiplierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_control::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
;
  }

  static const char* value(const ::spot_control::multiplierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_control::multiplierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_control::multiplierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_control::multiplierResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_CONTROL_MESSAGE_MULTIPLIERRESPONSE_H
