// Generated by gencpp from file spot_control/multiplier.msg
// DO NOT EDIT!


#ifndef SPOT_CONTROL_MESSAGE_MULTIPLIER_H
#define SPOT_CONTROL_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <spot_control/multiplierRequest.h>
#include <spot_control/multiplierResponse.h>


namespace spot_control
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace spot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spot_control::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::spot_control::multiplier&) { return value(); }
};

template<>
struct DataType< ::spot_control::multiplier > {
  static const char* value()
  {
    return "spot_control/multiplier";
  }

  static const char* value(const ::spot_control::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::spot_control::multiplierRequest> should match
// service_traits::MD5Sum< ::spot_control::multiplier >
template<>
struct MD5Sum< ::spot_control::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spot_control::multiplier >::value();
  }
  static const char* value(const ::spot_control::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_control::multiplierRequest> should match
// service_traits::DataType< ::spot_control::multiplier >
template<>
struct DataType< ::spot_control::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::spot_control::multiplier >::value();
  }
  static const char* value(const ::spot_control::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spot_control::multiplierResponse> should match
// service_traits::MD5Sum< ::spot_control::multiplier >
template<>
struct MD5Sum< ::spot_control::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spot_control::multiplier >::value();
  }
  static const char* value(const ::spot_control::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spot_control::multiplierResponse> should match
// service_traits::DataType< ::spot_control::multiplier >
template<>
struct DataType< ::spot_control::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::spot_control::multiplier >::value();
  }
  static const char* value(const ::spot_control::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPOT_CONTROL_MESSAGE_MULTIPLIER_H
